theme: jekyll-theme-tactile
maintainer:
  url: https://202accepted.com/
  icon: https://202accepted.com/images/favicon.ico
  name: 202Accepted
title: Jargon Terms Explained
description: A collection of articles which explain terminology neatly
